spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-database
    username: movie_user
    password: z8BFsHAQ4dGrm8R12SQCoTvG
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  access-token:
    expiration-time: 300000
    secret: 4XUagJh9fZZrWDBfsEe6wmL3eC4765cL
    header-name: Authorization
  refresh-token:
    expiration-time: 900000
    secret: j6EMM6EMYFeMXfEPVnx5rgKm7xWxb77U
    header-name: Refresh-token

cors:
  allowed-methods: "*"
  allowed-origins: "*"
  allowed-headers: "*"
  exposed-headers: Authorization,Content-Disposition,Refresh-token