spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-database
    username: movie_user
    password: z8BFsHAQ4dGrm8R12SQCoTvG
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: *
  liquibase:
    drop-first: true

mail:
  template:
    confirm-registration: d-d00f99de8c8c4fe8b697c546a0bace78

security:
  access-token:
    expiration-time: 300000
    secret: 4XUagJh9fZZrWDBfsEe6wmL3eC4765cL
    header-name: Authorization
  refresh-token:
    expiration-time: 900000
    secret: j6EMM6EMYFeMXfEPVnx5rgKm7xWxb77U
    header-name: Refresh-token
  confirmation-token:
    expiration-time: 86400000
    secret: PuRJkk4PtdjbvRfbGmFEREKgydjzLQ69

cors:
  allowed-methods: "*"
  allowed-origins: "*"
  allowed-headers: "*"
  exposed-headers: Authorization,Content-Disposition,Refresh-token
recaptcha:
  validation:
    secret-key: 6LdbWqQUAAAAAAcvQPa2D82_r8hd0WHJLOAWNwzO

movie-db:
  mail-sender: test@example.com
  application-url: http://localhost:8080
  frontend-url: http://localhost:4200

