spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-database
    username: movie_user
    password: z8BFsHAQ4dGrm8R12SQCoTvG
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    expiration-time: 92000
    secret: R88dSRdLC9nwxaNw
    header-name: Authorization
    header-prefix: Bearer