databaseChangeLog:
  - changeSet:
      id: 1
      author: arkadiusz.szast
      changes:
        - createTable:
            tableName: application_user
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: varchar(255)
                  constraints:
                    nullable: false,
                    unique: true
              - column:
                  name: password
                  type: varchar(255)
                  constraints:
                    nullable: false

